import React from 'react';
import { ForecastResult } from '../../types/agent';

interface ForecastChartProps {
  forecast: ForecastResult;
}

export const ForecastChart: React.FC<ForecastChartProps> = ({ forecast }) => {
  const points = forecast.predictedValues ?? [];
  const values = points
    .map(point => point.predicted)
    .filter((value): value is number =>
      typeof value === 'number' && Number.isFinite(value)
    );

  const intervals = points
    .map((point, index) => ({
      index,
      lower: point.lowerBound,
      upper: point.upperBound,
    }))
    .filter(
      item =>
        typeof item.lower === 'number' &&
        typeof item.upper === 'number' &&
        Number.isFinite(item.lower) &&
        Number.isFinite(item.upper),
    );

  if (!values.length) {
    return (
      <div className="popu-surface border border-[var(--popu-border)] rounded-2xl p-5">
        <div className="text-sm font-semibold text-[var(--popu-text)]">
          Epidemiological Projection
        </div>
        <div className="mt-3 text-xs text-[var(--popu-sub)]">
          No forecast values are available for this scenario.
        </div>
      </div>
    );
  }

  const chartHeight = 220;
  const chartWidth = 640;
  const paddingX = 45;
  const paddingY = 25;
  const maxVal = Math.max(
    1,
    ...values,
    ...intervals.map(item => item.upper as number),
  ) * 1.15;

  const getX = (index: number) =>
    values.length === 1
      ? chartWidth / 2
      : paddingX +
        (index / (values.length - 1)) *
          (chartWidth - paddingX * 2);

  const getY = (value: number) =>
    chartHeight -
    paddingY -
    (value / maxVal) * (chartHeight - paddingY * 2);

  const projectedPath = values
    .map(
      (value, index) =>
        `${index === 0 ? 'M' : 'L'} ${getX(index)} ${getY(value)}`,
    )
    .join(' ');

  const intervalPolygonPoints = [
    ...intervals.map(item => `${getX(item.index)},${getY(item.upper as number)}`),
    ...[...intervals].reverse().map(
      item => `${getX(item.index)},${getY(item.lower as number)}`,
    ),
  ].join(' ');

  const highestValue = Math.max(...values);
  const peakIndex = values.indexOf(highestValue);
  const expectedWeeklyIncidence = Math.round(
    values.slice(0, 7).reduce((sum, value) => sum + value, 0),
  );

  const trend =
    values.length < 2
      ? 'STABLE'
      : values[values.length - 1] > values[0]
        ? 'INCREASING'
        : values[values.length - 1] < values[0]
          ? 'DECREASING'
          : 'STABLE';

  return (
    <div className="popu-surface border border-[var(--popu-border)] rounded-2xl p-5">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 pb-4 border-b border-[var(--popu-border)]">
        <div>
          <div className="flex items-center gap-2 text-xs font-mono text-[var(--popu-sub)]">
            <span>MODEL OUTPUT</span>
            <span aria-hidden="true">-</span>
            <span>{forecast.modelName}</span>
            <span aria-hidden="true">-</span>
            <span>{forecast.modelVersion}</span>
          </div>
          <h4 className="text-base font-semibold text-[var(--popu-text)] mt-1">
            Epidemiological Projection
          </h4>
          <p className="text-xs text-[var(--popu-sub)] mt-1">
            Daily numerical forecast generated by the POPU forecasting service.
          </p>
        </div>
        <div className="text-xs font-mono text-[var(--popu-sub)]">
          {forecast.disease} - {forecast.geography}
        </div>
      </div>

      <div className="grid grid-cols-2 sm:grid-cols-4 gap-4 py-4 border-b border-[var(--popu-border)]/80">
        <div>
          <div className="text-xs uppercase font-mono text-[var(--popu-sub)]">Forecast Horizon</div>
          <div className="text-2xl font-mono font-semibold text-[var(--popu-text)] mt-0.5">
            {forecast.forecastHorizonDays} <span className="text-xs font-normal text-[var(--popu-sub)]">days</span>
          </div>
          <div className="text-xs text-[var(--popu-sub)] font-mono mt-0.5">Daily projected values</div>
        </div>
        <div>
          <div className="text-xs uppercase font-mono text-[var(--popu-sub)]">Forecast Risk</div>
          <div className="text-2xl font-mono font-semibold text-rose-400 mt-0.5">
            {forecast.riskScore} <span className="text-xs font-normal text-[var(--popu-sub)]">/ 100</span>
          </div>
          <div className="text-xs text-[var(--popu-sub)] font-mono mt-0.5">Model risk score</div>
        </div>
        <div>
          <div className="text-xs uppercase font-mono text-[var(--popu-sub)]">First 7 Days</div>
          <div className="text-2xl font-mono font-semibold text-[var(--popu-warning)] mt-0.5">~{expectedWeeklyIncidence}</div>
          <div className="text-xs text-[var(--popu-warning)]/80 font-mono mt-0.5">Sum of available daily projections</div>
        </div>
        <div>
          <div className="text-xs uppercase font-mono text-[var(--popu-sub)]">Direction</div>
          <div className="text-lg font-semibold text-[var(--popu-text)] mt-1.5 font-mono">{trend}</div>
          <div className="text-xs text-[var(--popu-sub)] font-mono mt-0.5">Highest value: Day +{peakIndex + 1}</div>
        </div>
      </div>

      <div className="mt-4 relative overflow-x-auto">
        <svg
          viewBox={`0 0 ${chartWidth} ${chartHeight}`}
          className="w-full h-auto min-w-[540px] text-[var(--popu-sub)] overflow-visible"
          role="img"
          aria-label="Daily epidemiological forecast with available prediction intervals"
        >
          {[0, 0.25, 0.5, 0.75, 1].map((pct, index) => {
            const y = chartHeight - paddingY - pct * (chartHeight - paddingY * 2);
            return (
              <g key={index}>
                <line
                  x1={paddingX}
                  y1={y}
                  x2={chartWidth - paddingX}
                  y2={y}
                  stroke="var(--popu-border)"
                  strokeWidth="1"
                  strokeDasharray="3 3"
                />
                <text
                  x={paddingX - 8}
                  y={y + 4}
                  textAnchor="end"
                  className="text-[10px] font-mono fill-[var(--popu-sub)]"
                >
                  {Math.round(pct * maxVal)}
                </text>
              </g>
            );
          })}

          {intervals.length > 1 && (
            <polygon
              points={intervalPolygonPoints}
              fill="var(--popu-teal)"
              fillOpacity="0.18"
              stroke="none"
            />
          )}

          <path
            d={projectedPath}
            fill="none"
            stroke="var(--popu-teal)"
            strokeWidth="2.5"
            strokeDasharray="5 4"
          />

          {values.map((value, index) => (
            <circle
              key={`forecast-${index}`}
              cx={getX(index)}
              cy={getY(value)}
              r="3.5"
              className="fill-[var(--popu-teal)] stroke-[var(--popu-surface)] stroke-1.5"
            />
          ))}

          {values.map((_, index) => {
            if (index % 3 !== 0 && index !== values.length - 1) return null;
            return (
              <text
                key={`label-${index}`}
                x={getX(index)}
                y={chartHeight - 6}
                textAnchor="middle"
                className="text-[9px] font-mono fill-[var(--popu-sub)]"
              >
                Day +{index + 1}
              </text>
            );
          })}
        </svg>

        <div className="flex flex-wrap items-center justify-between gap-4 mt-3 pt-3 border-t border-[var(--popu-border)]/60 text-xs font-mono">
          <div className="flex flex-wrap items-center gap-5">
            <div className="flex items-center gap-2">
              <span className="w-3 h-0.5 border-b border-dashed border-[var(--popu-teal)]" />
              <span className="text-[var(--popu-teal)]">Projected Trajectory</span>
            </div>
            {intervals.length > 1 && (
              <div className="flex items-center gap-2">
                <span className="w-3 h-2 bg-[var(--popu-teal)]/25 border border-[var(--popu-teal)]/40 rounded-sm" />
                <span className="text-[var(--popu-sub)]">Prediction Interval</span>
              </div>
            )}
          </div>
          <div className="text-[11px] text-[var(--popu-warning)]/90 font-mono tracking-tight bg-[var(--popu-warning)]/10 px-2 py-0.5 rounded border border-[var(--popu-warning)]/20">
            {forecast.dataStatus}
          </div>
        </div>
      </div>

      <div className="mt-4 p-3 bg-[var(--popu-muted)] border border-[var(--popu-border)] rounded-xl text-xs text-[var(--popu-sub)]">
        <strong>MODEL NOTE:</strong>{' '}
        Forecast values are model outputs based on synthetic demonstration data.
        They are not observed case counts and must be reviewed by a qualified
        epidemiologist before operational use.
      </div>
    </div>
  );
};
