import React from 'react';
import { ForecastResult } from '../../api/forecast';

interface ForecastChartProps {
  forecast: ForecastResult;
}

export const ForecastChart: React.FC<ForecastChartProps> = ({ forecast }) => {
  const values = forecast.predicted_values ?? [];
  const intervals = forecast.confidence_interval ?? [];

  if (!values.length) {
    return (
      <div className="popu-surface border border-[var(--popu-border)] rounded-2xl p-5">
        <div className="text-sm font-semibold text-[var(--popu-text)]">
          Epidemiological Projection
        </div>

        <div className="mt-3 text-xs text-[var(--popu-sub)]">
          No forecast values are available for this scenario.
        </div>
      </div>
    );
  }

  const chartHeight = 220;
  const chartWidth = 640;
  const paddingX = 45;
  const paddingY = 25;

  const maxVal =
    Math.max(
      ...values,
      ...intervals.map((item) => item.upper),
    ) * 1.15;

  const getX = (index: number) => {
    if (values.length === 1) {
      return chartWidth / 2;
    }

    return (
      paddingX +
      (index / (values.length - 1)) *
        (chartWidth - paddingX * 2)
    );
  };

  const getY = (value: number) => {
    return (
      chartHeight -
      paddingY -
      (value / Math.max(maxVal, 1)) *
        (chartHeight - paddingY * 2)
    );
  };

  const projectedPath = values
    .map(
      (value, index) =>
        `${index === 0 ? 'M' : 'L'} ${getX(index)} ${getY(value)}`,
    )
    .join(' ');

  const upperCoords = intervals.map(
    (item, index) =>
      `${getX(index)},${getY(item.upper)}`,
  );

  const lowerCoordsReversed = [...intervals]
    .reverse()
    .map((item, reverseIndex) => {
      const index = intervals.length - 1 - reverseIndex;

      return `${getX(index)},${getY(item.lower)}`;
    });

  const intervalPolygonPoints = [
    ...upperCoords,
    ...lowerCoordsReversed,
  ].join(' ');

  const highestValue = Math.max(...values);
  const peakIndex = values.indexOf(highestValue);

  const expectedWeeklyIncidence = Math.round(
    (values.reduce((sum, value) => sum + value, 0) /
      values.length) *
      7,
  );

  const trend =
    values.length > 1
      ? values[values.length - 1] > values[0]
        ? 'INCREASING'
        : values[values.length - 1] < values[0]
          ? 'DECREASING'
          : 'STABLE'
      : 'STABLE';

  return (
    <div className="popu-surface border border-[var(--popu-border)] rounded-2xl p-5">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 pb-4 border-b border-[var(--popu-border)]">
        <div>
          <div className="flex items-center gap-2 text-xs font-mono text-[var(--popu-sub)]">
            <span>MODEL OUTPUT</span>
            <span aria-hidden="true">-</span>
            <span>{forecast.model}</span>
            <span aria-hidden="true">-</span>
            <span>{forecast.model_version}</span>
          </div>

          <h4 className="text-base font-semibold text-[var(--popu-text)] mt-1">
            Epidemiological Projection
          </h4>

          <p className="text-xs text-[var(--popu-sub)] mt-1">
            Daily numerical forecast generated by the POPU forecasting service.
          </p>
        </div>

        <div className="text-xs font-mono text-[var(--popu-sub)]">
          {forecast.disease} - {forecast.geography}
        </div>
      </div>

      {/* Metrics */}
      <div className="grid grid-cols-2 sm:grid-cols-4 gap-4 py-4 border-b border-[var(--popu-border)]/80">
        <div>
          <div className="text-xs uppercase font-mono text-[var(--popu-sub)]">
            Forecast Horizon
          </div>

          <div className="text-2xl font-mono font-semibold text-[var(--popu-text)] mt-0.5">
            {forecast.forecast_horizon_days}{' '}
            <span className="text-xs font-normal text-[var(--popu-sub)]">
              days
            </span>
          </div>

          <div className="text-xs text-[var(--popu-sub)] font-mono mt-0.5">
            Daily projected values
          </div>
        </div>

        <div>
          <div className="text-xs uppercase font-mono text-[var(--popu-sub)]">
            Forecast Risk
          </div>

          <div className="text-2xl font-mono font-semibold text-rose-400 mt-0.5">
            {forecast.risk_score}{' '}
            <span className="text-xs font-normal text-[var(--popu-sub)]">
              / 100
            </span>
          </div>

          <div className="text-xs text-rose-400/80 font-mono mt-0.5">
            {forecast.risk_level}
          </div>
        </div>

        <div>
          <div className="text-xs uppercase font-mono text-[var(--popu-sub)]">
            Weekly Projection
          </div>

          <div className="text-2xl font-mono font-semibold text-[var(--popu-warning)] mt-0.5">
            ~{expectedWeeklyIncidence}
          </div>

          <div className="text-xs text-[var(--popu-warning)]/80 font-mono mt-0.5">
            Derived from forecast mean
          </div>
        </div>

        <div>
          <div className="text-xs uppercase font-mono text-[var(--popu-sub)]">
            Direction
          </div>

          <div className="text-lg font-semibold text-[var(--popu-text)] mt-1.5 font-mono">
            {trend}
          </div>

          <div className="text-xs text-[var(--popu-sub)] font-mono mt-0.5">
            Peak: Day +{peakIndex + 1}
          </div>
        </div>
      </div>

      {/* Chart */}
      <div className="mt-4 relative overflow-x-auto">
        <svg
          viewBox={`0 0 ${chartWidth} ${chartHeight}`}
          className="w-full h-auto min-w-[540px] text-[var(--popu-sub)] overflow-visible"
        >
          {/* Y grid */}
          {[0, 0.25, 0.5, 0.75, 1].map((pct, index) => {
            const y =
              chartHeight -
              paddingY -
              pct * (chartHeight - paddingY * 2);

            const value = Math.round(pct * maxVal);

            return (
              <g key={index}>
                <line
                  x1={paddingX}
                  y1={y}
                  x2={chartWidth - paddingX}
                  y2={y}
                  stroke="var(--popu-border)"
                  strokeWidth="1"
                  strokeDasharray="3 3"
                />

                <text
                  x={paddingX - 8}
                  y={y + 4}
                  textAnchor="end"
                  className="text-[10px] font-mono fill-[var(--popu-sub)]"
                >
                  {value}
                </text>
              </g>
            );
          })}

          {/* Prediction interval */}
          <polygon
            points={intervalPolygonPoints}
            fill="var(--popu-teal)"
            fillOpacity="0.18"
            stroke="none"
          />

          {/* Forecast line */}
          <path
            d={projectedPath}
            fill="none"
            stroke="var(--popu-teal)"
            strokeWidth="2.5"
            strokeDasharray="5 4"
          />

          {/* Forecast markers */}
          {values.map((value, index) => (
            <circle
              key={`forecast-${index}`}
              cx={getX(index)}
              cy={getY(value)}
              r="3.5"
              className="fill-[var(--popu-teal)] stroke-[var(--popu-surface)] stroke-1.5"
            />
          ))}

          {/* X axis */}
          {values.map((_, index) => {
            if (
              index % 3 !== 0 &&
              index !== values.length - 1
            ) {
              return null;
            }

            return (
              <text
                key={`label-${index}`}
                x={getX(index)}
                y={chartHeight - 6}
                textAnchor="middle"
                className="text-[9px] font-mono fill-[var(--popu-sub)]"
              >
                Day +{index + 1}
              </text>
            );
          })}
        </svg>

        {/* Legend */}
        <div className="flex flex-wrap items-center justify-between gap-4 mt-3 pt-3 border-t border-[var(--popu-border)]/60 text-xs font-mono">
          <div className="flex flex-wrap items-center gap-5">
            <div className="flex items-center gap-2">
              <span className="w-3 h-0.5 border-b border-dashed border-[var(--popu-teal)]" />
              <span className="text-[var(--popu-teal)]">
                Projected Trajectory
              </span>
            </div>

            <div className="flex items-center gap-2">
              <span className="w-3 h-2 bg-[var(--popu-teal)]/25 border border-[var(--popu-teal)]/40 rounded-sm" />
              <span className="text-[var(--popu-sub)]">
                Prediction Interval
              </span>
            </div>
          </div>

          <div className="text-[11px] text-[var(--popu-warning)]/90 font-mono tracking-tight bg-[var(--popu-warning)]/10 px-2 py-0.5 rounded border border-[var(--popu-warning)]/20">
            {forecast.data_status}
          </div>
        </div>
      </div>

      {/* Scientific notice */}
      <div className="mt-4 p-3 bg-[var(--popu-muted)] border border-[var(--popu-border)] rounded-xl text-xs text-[var(--popu-sub)] flex items-start gap-2.5">
        <span className="text-[var(--popu-teal)] font-mono shrink-0">
          MODEL NOTE:
        </span>

        <span className="leading-relaxed">
          {forecast.notice} The numerical forecast is produced by
          the deterministic POPU forecasting service. The LLM does
          not generate the numerical forecast values.
        </span>
      </div>

      {/* Uncertainty */}
      {forecast.uncertainty.length > 0 && (
        <div className="mt-3 p-3 bg-[var(--popu-muted)] border border-[var(--popu-border)] rounded-xl">
          <div className="text-xs font-mono text-[var(--popu-sub)] mb-2">
            UNCERTAINTY
          </div>

          <ul className="space-y-1">
            {forecast.uncertainty.map((item, index) => (
              <li
                key={index}
                className="text-xs text-[var(--popu-sub)]"
              >
                - {item}
              </li>
            ))}
          </ul>
        </div>
      )}
    </div>
  );
};